id = "pdtt"
name = "PDTT"
version = "0.0.1"
schema_version = 1
authors = ["pdtt contributors"]
description = "PDTT language support for Zed"
repository = "https://example.invalid/pdtt"
themes = []
icon_themes = []
languages = ["languages/pdtt"]
capabilities = []

[lib]

[grammars.pdtt]
repository = "https://github.com/vladtrc/pdtt"
rev = "ea6d0071e353a15a5a3bf11435533e3e8ee39b2a"
path = "tools/zed-pdtt/tree-sitter-pdtt"

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
