id = "pdtt"
name = "PDTT"
version = "0.0.1"
schema_version = 1
authors = ["pdtt contributors"]
description = "PDTT language support for Zed"
repository = "https://example.invalid/pdtt"
themes = []
icon_themes = []
languages = ["languages/pdtt"]
capabilities = []

[lib]

[grammars.pdtt]
repository = "https://github.com/vladtrc/pdtt"
rev = "7d97c4f89ab1ef0b4eb09ceaf090e7e5787824d0"
path = "tools/zed-pdtt/tree-sitter-pdtt"

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
