/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 9
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LF = 2,
  sym_comment = 3,
  sym_string = 4,
  sym_duration = 5,
  sym_percent = 6,
  sym_number = 7,
  sym_constant = 8,
  sym_modifier = 9,
  sym_keyword = 10,
  sym_arrow = 11,
  sym_bar = 12,
  sym_open_bracket = 13,
  sym_close_bracket = 14,
  sym_delimiter = 15,
  sym_operator = 16,
  sym_text = 17,
  sym_source_file = 18,
  sym_blank_line = 19,
  sym_line = 20,
  sym__item = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_line_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [sym_duration] = "duration",
  [sym_percent] = "percent",
  [sym_number] = "number",
  [sym_constant] = "constant",
  [sym_modifier] = "modifier",
  [sym_keyword] = "keyword",
  [sym_arrow] = "arrow",
  [sym_bar] = "bar",
  [sym_open_bracket] = "open_bracket",
  [sym_close_bracket] = "close_bracket",
  [sym_delimiter] = "delimiter",
  [sym_operator] = "operator",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_blank_line] = "blank_line",
  [sym_line] = "line",
  [sym__item] = "_item",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_line_repeat1] = "line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [sym_duration] = sym_duration,
  [sym_percent] = sym_percent,
  [sym_number] = sym_number,
  [sym_constant] = sym_constant,
  [sym_modifier] = sym_modifier,
  [sym_keyword] = sym_keyword,
  [sym_arrow] = sym_arrow,
  [sym_bar] = sym_bar,
  [sym_open_bracket] = sym_open_bracket,
  [sym_close_bracket] = sym_close_bracket,
  [sym_delimiter] = sym_delimiter,
  [sym_operator] = sym_operator,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_blank_line] = sym_blank_line,
  [sym_line] = sym_line,
  [sym__item] = sym__item,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_line_repeat1] = aux_sym_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_percent] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_open_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_close_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
};

static const TSCharacterRange sym_text_character_set_1[] = {
  {0, 0x08}, {0x0b, 0x0b}, {0x0e, 0x1f}, {'$', '$'}, {'&', '\''}, {'0', '9'}, {';', ';'}, {'A', 'Z'},
  {'\\', '\\'}, {'^', 'z'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '\n', 8,
        '!', 2,
        '"', 1,
        '#', 9,
        '-', 27,
        '.', 24,
        '<', 26,
        '=', 26,
        '>', 26,
        'a', 38,
        'b', 74,
        'c', 57,
        'e', 30,
        'h', 47,
        'i', 53,
        'l', 31,
        'm', 33,
        'o', 72,
        's', 71,
        't', 64,
        '|', 20,
        ',', 23,
        ':', 23,
        '(', 21,
        '[', 21,
        '{', 21,
        ')', 22,
        ']', 22,
        '}', 22,
      );
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '/') ||
          lookahead == '?' ||
          lookahead == '@') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 4:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 5:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_duration);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_duration);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_percent);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(13);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == 's') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(13);
      if (lookahead == 's') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_constant);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_modifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_modifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_arrow);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_bar);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_open_bracket);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_close_bracket);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_delimiter);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_delimiter);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '>') ADVANCE(19);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(68);
      if (lookahead == 'p') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(59);
      if (lookahead == 'r') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_text);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(76);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(12);
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_keyword);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(21);
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(7);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(7);
      END_STATE();
    case 21:
      if (lookahead == 'g') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(7);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 32:
      if (lookahead == 'h') ADVANCE(33);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [sym_percent] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_constant] = ACTIONS(1),
    [sym_modifier] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_arrow] = ACTIONS(1),
    [sym_bar] = ACTIONS(1),
    [sym_open_bracket] = ACTIONS(1),
    [sym_close_bracket] = ACTIONS(1),
    [sym_delimiter] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(8),
    [sym_blank_line] = STATE(2),
    [sym_line] = STATE(2),
    [sym__item] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_line_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym_string] = ACTIONS(9),
    [sym_duration] = ACTIONS(5),
    [sym_percent] = ACTIONS(9),
    [sym_number] = ACTIONS(5),
    [sym_constant] = ACTIONS(9),
    [sym_modifier] = ACTIONS(5),
    [sym_keyword] = ACTIONS(5),
    [sym_arrow] = ACTIONS(9),
    [sym_bar] = ACTIONS(9),
    [sym_open_bracket] = ACTIONS(9),
    [sym_close_bracket] = ACTIONS(9),
    [sym_delimiter] = ACTIONS(5),
    [sym_operator] = ACTIONS(5),
    [sym_text] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_blank_line] = STATE(3),
    [sym_line] = STATE(3),
    [sym__item] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_line_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym_string] = ACTIONS(9),
    [sym_duration] = ACTIONS(5),
    [sym_percent] = ACTIONS(9),
    [sym_number] = ACTIONS(5),
    [sym_constant] = ACTIONS(9),
    [sym_modifier] = ACTIONS(5),
    [sym_keyword] = ACTIONS(5),
    [sym_arrow] = ACTIONS(9),
    [sym_bar] = ACTIONS(9),
    [sym_open_bracket] = ACTIONS(9),
    [sym_close_bracket] = ACTIONS(9),
    [sym_delimiter] = ACTIONS(5),
    [sym_operator] = ACTIONS(5),
    [sym_text] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym_blank_line] = STATE(3),
    [sym_line] = STATE(3),
    [sym__item] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_line_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_LF] = ACTIONS(18),
    [sym_comment] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_duration] = ACTIONS(15),
    [sym_percent] = ACTIONS(21),
    [sym_number] = ACTIONS(15),
    [sym_constant] = ACTIONS(21),
    [sym_modifier] = ACTIONS(15),
    [sym_keyword] = ACTIONS(15),
    [sym_arrow] = ACTIONS(21),
    [sym_bar] = ACTIONS(21),
    [sym_open_bracket] = ACTIONS(21),
    [sym_close_bracket] = ACTIONS(21),
    [sym_delimiter] = ACTIONS(15),
    [sym_operator] = ACTIONS(15),
    [sym_text] = ACTIONS(15),
  },
  [STATE(4)] = {
    [sym__item] = STATE(5),
    [aux_sym_line_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(24),
    [anon_sym_LF] = ACTIONS(26),
    [sym_comment] = ACTIONS(28),
    [sym_string] = ACTIONS(28),
    [sym_duration] = ACTIONS(24),
    [sym_percent] = ACTIONS(28),
    [sym_number] = ACTIONS(24),
    [sym_constant] = ACTIONS(28),
    [sym_modifier] = ACTIONS(24),
    [sym_keyword] = ACTIONS(24),
    [sym_arrow] = ACTIONS(28),
    [sym_bar] = ACTIONS(28),
    [sym_open_bracket] = ACTIONS(28),
    [sym_close_bracket] = ACTIONS(28),
    [sym_delimiter] = ACTIONS(24),
    [sym_operator] = ACTIONS(24),
    [sym_text] = ACTIONS(24),
  },
  [STATE(5)] = {
    [sym__item] = STATE(5),
    [aux_sym_line_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(30),
    [anon_sym_LF] = ACTIONS(33),
    [sym_comment] = ACTIONS(35),
    [sym_string] = ACTIONS(35),
    [sym_duration] = ACTIONS(30),
    [sym_percent] = ACTIONS(35),
    [sym_number] = ACTIONS(30),
    [sym_constant] = ACTIONS(35),
    [sym_modifier] = ACTIONS(30),
    [sym_keyword] = ACTIONS(30),
    [sym_arrow] = ACTIONS(35),
    [sym_bar] = ACTIONS(35),
    [sym_open_bracket] = ACTIONS(35),
    [sym_close_bracket] = ACTIONS(35),
    [sym_delimiter] = ACTIONS(30),
    [sym_operator] = ACTIONS(30),
    [sym_text] = ACTIONS(30),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(38),
    [sym_identifier] = ACTIONS(40),
    [anon_sym_LF] = ACTIONS(38),
    [sym_comment] = ACTIONS(38),
    [sym_string] = ACTIONS(38),
    [sym_duration] = ACTIONS(40),
    [sym_percent] = ACTIONS(38),
    [sym_number] = ACTIONS(40),
    [sym_constant] = ACTIONS(38),
    [sym_modifier] = ACTIONS(40),
    [sym_keyword] = ACTIONS(40),
    [sym_arrow] = ACTIONS(38),
    [sym_bar] = ACTIONS(38),
    [sym_open_bracket] = ACTIONS(38),
    [sym_close_bracket] = ACTIONS(38),
    [sym_delimiter] = ACTIONS(40),
    [sym_operator] = ACTIONS(40),
    [sym_text] = ACTIONS(40),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(42),
    [sym_identifier] = ACTIONS(44),
    [anon_sym_LF] = ACTIONS(42),
    [sym_comment] = ACTIONS(42),
    [sym_string] = ACTIONS(42),
    [sym_duration] = ACTIONS(44),
    [sym_percent] = ACTIONS(42),
    [sym_number] = ACTIONS(44),
    [sym_constant] = ACTIONS(42),
    [sym_modifier] = ACTIONS(44),
    [sym_keyword] = ACTIONS(44),
    [sym_arrow] = ACTIONS(42),
    [sym_bar] = ACTIONS(42),
    [sym_open_bracket] = ACTIONS(42),
    [sym_close_bracket] = ACTIONS(42),
    [sym_delimiter] = ACTIONS(44),
    [sym_operator] = ACTIONS(44),
    [sym_text] = ACTIONS(44),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [24] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_line_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pdtt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pdtt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
