name = "PDTT"
grammar = "pdtt"
path_suffixes = ["pdtt"]
line_comments = ["# "]
tab_size = 2
hard_tabs = false
brackets = [
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
